name: E2E (React + Selenium)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome-debug:latest
        ports:
          - 4444:4444
          - 5900:5900
        options: >-
          --shm-size=2g
          --health-cmd="curl -fsSL http://localhost:4444/status | jq -e '.value.ready == true' || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

      web:
        image: nginx:alpine
        ports:
          - 3000:80
        volumes:
          - ./dist:/usr/share/nginx/html:ro
        options: >-
          --health-cmd="wget -qO- http://localhost || exit 1"
          --health-interval=10s
          --health-timeout=5s
